# Generated by Django 5.1.4 on 2025-01-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roel',
            new_name='role',
        ),
    ]
