# Generated by Django 5.1.4 on 2025-01-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suivi_utilisateurs',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='commentaires',
            new_name='UserTracking',
        ),
    ]
